#!/usr/bin/python3
import subprocess
import re
import statistics
import math
import sys
import platform
import os.path
import psutil

def erf_inv(x):
    """Inverse of math.erf()"""
    a = 8 * (math.pi - 3) / (3 * math.pi*(4 - math.pi))
    y = math.log(1 - x * x)
    z = 2 / (math.pi * a) + y / 2
    return math.copysign(math.sqrt(math.sqrt(z * z - y / a) - z), x)

def CDF(q):
    """CDF of the standard Gaussian law"""
    return 0.5 * (1 + math.erf(q / math.sqrt(2)))

def Quantile(p):
    """Quantile function of the standard Gaussian law"""
    assert(0 <= p and p <= 1)
    return math.sqrt(2)*erf_inv(2*p-1)

def rightstr(s, l):
    if len(s) > l:
        return "..."+s[3-l:]
    else:
        return s

def stats(base, test, diff):
    runs = len(base)
    assert len(test) == runs == len(diff)
    assert runs >= 2
    base_mean = statistics.mean(base)
    test_mean = statistics.mean(test)
    diff_mean = statistics.mean(diff)
    base_sdev = statistics.stdev(base, base_mean) / math.sqrt(runs)
    test_sdev = statistics.stdev(test, test_mean) / math.sqrt(runs)
    diff_sdev = statistics.stdev(diff, diff_mean) / math.sqrt(runs)
    return (base_mean, base_sdev), (test_mean, test_sdev), (diff_mean, diff_sdev)

if (len(sys.argv) not in {4, 5} or int(sys.argv[3]) < 2):
    exit("Usage:\n" + sys.argv[0] + " base test #runs [depth] \nwhere #runs >= 2")

base, test, diff = [], [], []
runs = int(sys.argv[3])
depth = int(sys.argv[4]) if len(sys.argv) >= 5 else 13

exp = re.compile(br"Nodes/second\s*: (\d+)")

# determine CPU sets to run on
# this assumes that logical cpus on the same core are numbered sequentially
num_cores = psutil.cpu_count(logical=False)
num_cpus = psutil.cpu_count()

cpu_step = int(num_cpus / num_cores)
cpuset = []
cpuset.append(list())
cpuset.append(list())
for i in range(0, cpu_step):
    cpuset[0].extend(list(range(i, num_cpus, cpu_step*2)))
    cpuset[1].extend(list(range(i+cpu_step, num_cpus, cpu_step*2)))

cpuset = [[10, 11], [8, 9]]
print("{:>3} {:>10} {:>10} {:>8}".format("run","base","test","diff"))

GREEN = "\033[32m"
RED = "\033[31m"
RESET = "\033[0m"

hash = int(16 * 2**(max(0, (depth - 13) / 2)))

# cmd = f"bench {hash} 1 {depth}"
cmd = f"speedtest 1 16 50"

print(f'command: {cmd}')

i = 0
try:
    for i in range(runs):
        if i > 1:
            (base_mean, base_sdev), \
            (test_mean, test_sdev), \
            (diff_mean, diff_sdev) = stats(base, test, diff)
            print(f"mean{int(base_mean + .5):>10n} {int(test_mean + .5):>10n} "
                  + (GREEN if diff_mean > 0 else RED) * (abs(diff_mean) > 2*diff_sdev) +
                f"{100 * diff_mean:>+7.2f}{RESET} +- {diff_sdev:.2%}",
                  end='', flush=True)
        # Start both processes. This is non-blocking.
        base_process = subprocess.Popen([sys.argv[1], cmd], stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        psutil.Process(base_process.pid).cpu_affinity(cpuset[i%2])
        test_process = subprocess.Popen([sys.argv[2], cmd], stdout=subprocess.DEVNULL, stderr=subprocess.PIPE)
        psutil.Process(test_process.pid).cpu_affinity(cpuset[(i+1)%2])

        # Wait for processes to finish and grep nps results in their stderr output
        base.append(int(exp.search(base_process.stderr.read()).group(1)))
        test.append(int(exp.search(test_process.stderr.read()).group(1)))

        diff.append(test[i] / base[i] - 1)
        print("\r" + " " * 45, end='') # clear previous line
        def format_diff(num):
            COLOR = (RED, GREEN)
            sign = num >= 0
            s = f'{num:>+7.1%}'
            if abs(num) > .0025:
                return COLOR[sign] + s + RESET
            elif abs(num) > .001:
                digits = len(f'{num:.1%}')
                return COLOR[sign] + s[:-digits] + RESET + s[-digits:]
            else:
                return s
        print(f"\r{i+1:>3} {base[i]:>10n} {test[i]:>10n} {format_diff(diff[i])}" + RESET)
except KeyboardInterrupt:
    runs = i
    if i < 2 or not len(base) == len(test) == len(diff) == runs:
        raise

(base_mean, base_sdev), (test_mean, test_sdev), (diff_mean, diff_sdev) = stats(base, test, diff)

try:
    from scipy.stats import t
    CDF = t(runs - 1).cdf
    Quantile = t(runs - 1).ppf
    comment = "[95% CI; t-statistic]"
except ImportError:
    t = None
    comment = "[95% CI]"

if len(diff) > 2 and len(diff) % 2 == 0:
    n = len(diff) / 2
    diff1_sdev = statistics.stdev(diff[::2]) / math.sqrt(n)
    diff2_sdev = statistics.stdev(diff[1::2]) / math.sqrt(n)
    diff_sdev = math.sqrt(diff1_sdev**2 + diff2_sdev**2) / 2
    # sdev2_ = statistics.stdev([(x+y)/2 for x, y in zip(diff[::2], diff[1::2])]) / math.sqrt(len(diff) / 2)
    if t is not None:
        CDF = t(runs - 2).cdf
        Quantile = t(runs - 2).ppf

print("\nResult of {:3n} runs\n==================".format(runs))
print("base ({:<15s}) = {:>10n}  +/- {:n}".format(rightstr(sys.argv[1],15), round(base_mean), round(Quantile(0.975) * base_sdev)))
print("test ({:<15s}) = {:>10n}  +/- {:n}".format(rightstr(sys.argv[2],15), round(test_mean), round(Quantile(0.975) * test_sdev)))
# print("{:22s} = {:>+10n}  +/- {:n}".format("diff", round(diff_mean), round(Quantile(0.975) * diff_sdev)))

print(f"speedup %              =   {100 * diff_mean:>+8.2f}  +/- {100 * diff_sdev * Quantile(0.975):.2f}")
print(" " * 25 + comment)
print()

print(f"p(speedup > 0)   = {CDF(diff_mean / diff_sdev):>7.4f}")
# this number is basically p-value. If there is not speedup, the probability of this saying p(...) > 1 - p is less than p
if p05 := CDF((diff_mean - .005) / diff_sdev) > 0.01:
    print(f"p(speedup > .5%) = {p05}")

cpu = str()
if os.path.exists("/proc/cpuinfo"):
    exp = re.compile (r"^model name\s+:\s+(.*)$")
    with open('/proc/cpuinfo','r') as infile:
        for line in infile:
            m = exp.match(line)
            if m:
                cpu = m.group(1)
                break
if cpu == "":
    cpu = platform.processor()
if cpu == "":
    cpu = "unknown"
print ("\nCPU:",num_cores,"x",cpu)
print ("Hyperthreading:", "off" if num_cpus==num_cores else "on","\n")
