#!/usr/bin/python3
import subprocess
import select
import re
import statistics
import math
import sys
import platform
import os.path
import psutil
from time import sleep, perf_counter

def erf_inv(x):
    """Inverse of math.erf()"""
    a = 8 * (math.pi - 3) / (3 * math.pi*(4 - math.pi))
    y = math.log(1 - x * x)
    z = 2 / (math.pi * a) + y / 2
    return math.copysign(math.sqrt(math.sqrt(z * z - y / a) - z), x)

def CDF(q):
    """CDF of the standard Gaussian law"""
    return 0.5 * (1 + math.erf(q / math.sqrt(2)))

def Quantile(p):
    """Quantile function of the standard Gaussian law"""
    assert(0 <= p and p <= 1)
    return math.sqrt(2)*erf_inv(2*p-1)

def rightstr(s, l):
    if len(s) > l:
        return "..."+s[3-l:]
    else:
        return s

def parse_cycles(out):
    return int( RE_CYCLES.search(out).group(1).replace(',', '') )

def stats(base, test, diff):
    runs = len(base)
    assert len(test) == runs == len(diff)
    assert runs >= 2
    base_mean = statistics.mean(base)
    test_mean = statistics.mean(test)
    diff_mean = statistics.mean(diff)
    base_sdev = statistics.stdev(base, base_mean) / math.sqrt(runs)
    test_sdev = statistics.stdev(test, test_mean) / math.sqrt(runs)
    diff_sdev = statistics.stdev(diff, diff_mean) / math.sqrt(runs)
    return (base_mean, base_sdev), (test_mean, test_sdev), (diff_mean, diff_sdev)

RE_CYCLES = re.compile(r"([0-9,]*)\s+cpu_core/cpu-cycles")
RE_NODES = re.compile(r"^Nodes searched\s*: (\d+)", re.MULTILINE)

GREEN = "\033[32m"
RED = "\033[31m"
RESET = "\033[0m"

spd_nodes = False
if (len(sys.argv) == 5 and sys.argv[4] in {'stc', 'ltc'}):
    spd_nodes = sys.argv[4]
    RE_NODES = re.compile(r"Total nodes searched\s*: (\d+)")
elif (len(sys.argv) not in {4, 5} or int(sys.argv[3]) < 2):
    exit("Usage:\n" + sys.argv[0] + " base test #runs [depth] \nwhere #runs >= 2")

base, test, diff = [], [], []
runs = int(sys.argv[3])

if not spd_nodes:
    depth = int(sys.argv[4]) if len(sys.argv) >= 5 else 13
else:
    depth = -1

# determine CPU sets to run on
# this assumes that logical cpus on the same core are numbered sequentially
num_cores = psutil.cpu_count(logical=False)
num_cpus = psutil.cpu_count()

# cpuset = [[1, 2, 6, 7], [10, 11, 8, 9]]
# CES: some cores are faster than others:
# [10, 11] >> [6, 7]
# [10, 11] ~~ [8, 9]
# [6, 7] >> [1, 2]
# [10, 11] >> [1, 2]
# [1, 2] > [3, 4]
# [0, 5] ~~ [3, 4]
cpuset = [[10, 11], [8, 9]]
print("{:>3} {:>10} {:>10} {:>6}".format("run","base","test","diff"))


if not spd_nodes:
    hash = int(16 * 2**(max(0, (depth - 13) / 2)))
    cmd = f"bench {hash} 1 {depth}"
elif spd_nodes == 'stc':
    # cmd = f"speedtest 1 16 75 nodestime"
    cmd = f"speedtest 1 16 50"
    # cmd = f"speedtest 1 8 25"
elif spd_nodes == 'ltc':
    cmd = f"speedtest 1 64 450 nodestime"
else:
    raise ValueError(f'unknown time control {spd_nodes}')

print(f'command: {cmd}')

def start_engine(path):
    return subprocess.Popen(
        [path],
        stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.PIPE,
        encoding="utf8"
    )

def and_affinity(pid, cpuset):
    proc = psutil.Process(pid)
    proc.cpu_affinity(set(cpuset) & set(proc.cpu_affinity()))

warned = False
sample_no = 0
try:
    while sample_no < runs:
        if sample_no > 1:
            (base_mean, base_sdev), \
            (test_mean, test_sdev), \
            (diff_mean, diff_sdev) = stats(base, test, diff)
            print(f"mean{int(base_mean + .5):>10n} {int(test_mean + .5):>10n} "
                  + (GREEN if diff_mean > 0 else RED) * (abs(diff_mean) > 2*diff_sdev) +
                f"{100 * diff_mean:>+7.2f}{RESET} +- {diff_sdev:.2%}",
                  end='', flush=True)

        # Start both processes. This is non-blocking.
        base_proc = start_engine(sys.argv[1])
        and_affinity(base_proc.pid, cpuset[sample_no % 2])

        test_proc = start_engine(sys.argv[2])
        and_affinity(test_proc.pid, cpuset[(sample_no + 1) % 2])

        # send uci and wait for each engine to reply "uciok"
        for p in (base_proc, test_proc)[:: (-1)**( sample_no%4 in {0, 3} )]:
            p.stdin.write("uci\n")
            p.stdin.flush()

        pending = {base_proc.stdout, test_proc.stdout}
        while pending:
            r, _, _ = select.select(list(pending), [], [])
            for f in r:
                line = f.readline() # it seems like readline() is ok, but readlines() is not
                if line.startswith('id name'):
                    pending.remove(f)
            sleep(0.001)


        perfs = [
            subprocess.Popen(["perf", "stat", '-p', str(proc.pid)],
                             stderr=subprocess.PIPE, encoding='utf8')
            for proc in (base_proc, test_proc)
        ]
        sleep(0.3)

        def start(proc):
            proc.stdin.write(cmd + '\nquit\n')
            proc.stdin.flush()

        # run bench
        # then wait for processes to finish ...
        if sample_no % 4 in {0, 1}:
            start(test_proc)
            start(base_proc)
            # whichever process comes second here is falsely shown to have higher nodes per cycle, which is why we need to alternate
            _, out_t = test_proc.communicate()
            _, out_b = base_proc.communicate()
        else:
            start(base_proc)
            start(test_proc)
            _, out_b = base_proc.communicate()
            _, out_t = test_proc.communicate()


        # ... and grep nps results in their stderr output
        nodes = [int(RE_NODES.search(out).group(1)) for out in (out_b, out_t)]
        if nodes[1] == 0:
            nodes[1] = nodes[0]
        if not warned and nodes[0] != nodes[1]:
            print("WARN:  signature differs")
            warned = True

        for p, stat, nd in list(zip(perfs, (base, test), nodes)):
            p.send_signal(2)  # make perf print its output
            perf = p.stderr.read()
            cycles = parse_cycles(perf)
            stat.append(int(nd / cycles * 1e9))

        diff.append(math.log(test[sample_no] / base[sample_no]))
        # if spd_nodes and sample_no == 0:
        #     for name, out in (('base', stats_b), ('test', stats_t)):
        #         start = out.find('TT size [MiB]')
        #         lines = out[start:].split('\n')
        #         print(f'output from {name}:')
        #         print('\n'.join('  ' + x for x in lines[:6]))

        print("\r" + " " * 45, end='') # clear previous line
        def format_diff(num):
            COLOR = (RED, GREEN)
            sign = num >= 0
            s = f'{num:>+7.1%}'
            if abs(num) > .0025:
                return COLOR[sign] + s + RESET
            elif abs(num) > .001:
                digits = len(f'{num:.1%}')
                return COLOR[sign] + s[:-digits] + RESET + s[-digits:]
            else:
                return s
        print(f"\r{sample_no+1:>3} {base[sample_no]:>10n} {test[sample_no]:>10n} {format_diff(diff[sample_no])}" + RESET)
        if abs(diff[-1]) > math.log(2):
            print('  ^^^^ discarding this ^^^^')
            diff = diff[:-1]
            base = base[:-1]
            test = test[:-1]
            continue
        sample_no += 1
except KeyboardInterrupt:
    print("\r" + " " * 345, end='') # clear previous line
    if sample_no < 2 or not len(base) == len(test) == len(diff) == sample_no:
        raise

(base_mean, base_sdev), (test_mean, test_sdev), (diff_mean, diff_sdev) = stats(base, test, diff)
try:
    from scipy.stats import t
    CDF = t(sample_no - 1).cdf
    Quantile = t(sample_no - 1).ppf
    comment = "[95% CI; t-statistic]"
except ImportError:
    t = None
    comment = "[95% CI]"

if len(diff) > 2 and len(diff) % 2 == 0:
    n = len(diff) / 2
    diff1_sdev = statistics.stdev(diff[::2]) / math.sqrt(n)
    diff2_sdev = statistics.stdev(diff[1::2]) / math.sqrt(n)
    diff_sdev = math.sqrt(diff1_sdev**2 + diff2_sdev**2) / 2
    # sdev2_ = statistics.stdev([(x+y)/2 for x, y in zip(diff[::2], diff[1::2])]) / math.sqrt(len(diff) / 2)
    if t is not None:
        CDF = t(sample_no - 2).cdf
        Quantile = t(sample_no - 2).ppf

n = "hi"

print(f"\nResult of {sample_no} runs (cycles)\n===========================")
print("base ({:<15s}) = {:>10n}  +/- {:n}".format(rightstr(sys.argv[1],15), round(base_mean), round(Quantile(0.975) * base_sdev)))
print("test ({:<15s}) = {:>10n}  +/- {:n}".format(rightstr(sys.argv[2],15), round(test_mean), round(Quantile(0.975) * test_sdev)))
# print("{:22s} = {:>+10n}  +/- {:n}".format("diff", round(diff_mean), round(Quantile(0.975) * diff_sdev)))

speedup = math.exp(diff_mean) - 1
sp_unc = math.exp(diff_mean) * diff_sdev
print(f"speedup %              =   {100 * speedup:>+8.2f}  +/- {100 * sp_unc * Quantile(0.975):.2f}")
print(" " * 25 + comment)
print()

print(f"p(speedup > 0)   = {CDF(diff_mean / diff_sdev):>7.4f}")
# this number is basically p-value. If there is not speedup, the probability of this saying p(...) > 1 - p is less than p
if (p05 := CDF((diff_mean - math.log(1.005)) / diff_sdev)) > 0.01 or speedup > 1.025:
    print(f"p(speedup > .5%) = {p05:>7.4f}")

cpu = str()
if os.path.exists("/proc/cpuinfo"):
    exp = re.compile (r"^model name\s+:\s+(.*)$")
    with open('/proc/cpuinfo','r') as infile:
        for line in infile:
            m = exp.match(line)
            if m:
                cpu = m.group(1)
                break
if cpu == "":
    cpu = platform.processor()
if cpu == "":
    cpu = "unknown"
print ("\nCPU:",num_cores,"x",cpu)
print ("Hyperthreading:", "off" if num_cpus==num_cores else "on","\n")
